spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: homeworkdb
      username: root
      password: pass
      authentication-database: admin

  main:
    allow-circular-references: true

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mongock.changelog