version: '3.3' #format version for this docker compose file
services:
  mongo-container:
    image: mongo:latest
    container_name: mongo_db_otus
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    command: mongod
